name: kpacubo
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=35.0.0
  - cycler=0.11.0
  - debugpy=1.4.1
  - decorator=4.4.2
  - et_xmlfile=1.1.0
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=68.2
  - idna=3.2
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - joblib=1.1.0
  - jpeg=9d
  - jupyter_client=6.1.7
  - jupyter_core=4.8.1
  - kiwisolver=1.3.2
  - libclang=11.1.0
  - libiconv=1.15
  - libpng=1.6.37
  - libtiff=4.0.10
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - pandas=1.3.3
  - pandas-datareader=0.10.0
  - parso=0.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prompt-toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pywavelets=1.1.1
  - pywin32=228
  - pyzmq=22.2.1
  - qt=5.12.9
  - requests=2.26.0
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021e
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
